---
version: "3.9"

services:
  rapidpro:
    image: jozian/rapidpro:latest
    build:
      context: .
      target: rapidpro
    depends_on:
      - postgresql
      - redis
      - elasticsearch
      - courier
      - mailroom
    environment:
      - PUBLIC_HOSTNAME=${HOSTNAME}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/15
      - SECRET_KEY=${SECRET_KEY}
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=${MAILROOM_AUTH_TOKEN}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - S3_ENABLED=${S3_ENABLED}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    networks:
      - rapidpro
    volumes:
      - ../rapidpro-data/rapidpro/settings.py.dev.docker:/srv/rapidpro/rapidpro/temba/settings.py
      - ../rapidpro-data/rapidpro/sitestatic:/srv/rapidpro/rapidpro/sitestatic

  postgresql:
    # TODO: Update this image
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - rapidpro
    volumes:
      - ../rapidpro-data/db/data:/var/lib/postgresql/data

  redis:
    image: redis:6-buster
    networks:
      - rapidpro

  elasticsearch:
    image: elasticsearch:7.17.26
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - rapidpro
    volumes:
      - ../rapidpro-data/es/data:/usr/share/elasticsearch/data

  mailroom:
    image: jozian/mailroom:latest
    build:
      context: ../mailroom
    command: ["app", "-address", "0.0.0.0"]
    depends_on:
      - elasticsearch
      - postgresql
      - redis
    environment:
      - MAILROOM_DOMAIN=${HOSTNAME}
      - MAILROOM_ATTACHMENT_DOMAIN=${HOSTNAME}
      - MAILROOM_AUTH_TOKEN=${MAILROOM_AUTH_TOKEN}
      - MAILROOM_DB=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - MAILROOM_REDIS=redis://redis:6379/15
      - MAILROOM_ELASTIC=http://elasticsearch:9200
      - MAILROOM_LOG_LEVEL=debug
    networks:
      - rapidpro

  courier:
    image: jozian/courier:latest
    build:
      context: ../courier
    depends_on:
      - postgresql
      - redis
    environment:
      - COURIER_DOMAIN=${HOSTNAME}
      - COURIER_SPOOL_DIR=/srv/courier/spool
      - COURIER_DB=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - COURIER_REDIS=redis://redis:6379/15
    networks:
      - rapidpro
    volumes:
      - ../rapidpro-data/courier/spool:/srv/courier/spool

  rp-celery:
    image: jozian/rp-celery:latest
    build:
      context: .
      dockerfile: Dockerfile.celery
      target: rp-celery
    depends_on:
      - rapidpro
      - mailroom
      - elasticsearch
      - redis
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/15
      - SECRET_KEY=${SECRET_KEY}
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=${MAILROOM_AUTH_TOKEN}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - S3_ENABLED=${S3_ENABLED}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    networks:
      - rapidpro
    volumes:
      - ../rapidpro-data/rapidpro/settings.py.dev.docker:/srv/rp-celery/rapidpro/temba/settings.py
      - ../rapidpro-data/celery/schedule:/srv/rp-celery/schedule

  rp-indexer:
    image: jozian/rp-indexer:latest
    build:
      context: ../rp-indexer
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
    networks:
      - rapidpro

#  rp-archiver:
#    image: jozian/rp-archiver:latest
#    build:
#      context: ../rp-archiver
#        #    depends_on:
#        # - postgresql
#    environment:
#      - ARCHIVER_DB=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}?sslmode=require
#      - ARCHIVER_TEMP_DIR=/srv/rp-archiver/tmp
#      - ARCHIVER_DELETE=true
#    networks:
#      - rapidpro
#    volumes:
#      - ../rapidpro-data/rp-archiver/tmp:/srv/rp-archiver/tmp

# TODO: Put back rp-discord-proxy

networks:
  rapidpro:
    external: true
