---
version: "3.9"

services:
  caddy:
    image: "caddy:2.9.1-alpine"
    environment:
      - PUBLIC_HOSTNAME=${HOSTNAME}
    volumes:
      - "../rapidpro-data/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "../rapidpro-data/caddy/data:/data"
      - "../rapidpro-data/rapidpro/sitestatic:/mnt/sitestatic:ro"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rapidpro

  rapidpro:
    environment:
      - RAPIDPRO_ENV=production
      - RAPIDPRO_STORAGE_URL=https://${HOSTNAME}/media
    restart: always

  mailroom:
    restart: always

  courier:
    restart: always

  rp-celery:
    restart: always

  rp-indexer:
    restart: always

  redis:
    restart: always

  elasticsearch:
    restart: always


