apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: courier-deploy
  name: courier-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: courier
status:
  loadBalancer: {}
