apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: temba-postgres
  namespace: default

spec:

   replicas: 3
   image: postgis/postgis:12-3.0

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
